//USER CONSTANTS
export const USERS = "users";
export const FETCH_USER = "FETCH_USER";
export const CHANGE_IMG = "CHANGE_IMG";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

//RECIPES CONSTANTS
export const RECIPES = "recipes";
export const FETCH_RECIPE = "FETCH_RECIPE";
export const SAVE_RECIPE = "SAVE_RECIPE";
export const SAVE_RECIPE_IMAGE_NAME = "SAVE_RECIPE_IMAGE_NAME";
export const SAVE_RECIPE_GALLERY = "SAVE_RECIPE_GALLERY";
export const SAVE_RECIPE_INGREDIENTS = "SAVE_RECIPE_INGREDIENTS";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const FETCH_ALL_RECIPES = "FETCH_ALL_RECIPES";

export const SAVE_NAME_IMAGE_LOADING = "SAVE_NAME_IMAGE_LOADING";
export const SAVE_GALLERY_LOADING = "SAVE_GALLERY_LOADING";
export const SAVE_INGREDIENTS_LOADING = "SAVE_INGREDIENTS_LOADING";
export const SAVE_REST_LOADING = "SAVE_REST_LOADING";
export const FETCH_ALL_RECIPES_LOADING = "FETCH_ALL_RECIPES_LOADING";

//UTILS' CONSTANTS
export const SWITCH_LOADING = "SWITCH_LOADING";